// File generated by FlutterFire CLI.
// Manual creation based on Firebase project: bustracker-afb3c

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL_ErLShoU32Nkh6Rq8ODf3vYwsRM1r9A',
    appId: '1:851331446616:web:5ec0bd8140872810f1d72d',
    messagingSenderId: '851331446616',
    projectId: 'bustracker-afb3c',
    authDomain: 'bustracker-afb3c.firebaseapp.com',
    storageBucket: 'bustracker-afb3c.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL_ErLShoU32Nkh6Rq8ODf3vYwsRM1r9A',
    appId: '1:851331446616:android:5ec0bd8140872810f1d72d',
    messagingSenderId: '851331446616',
    projectId: 'bustracker-afb3c',
    storageBucket: 'bustracker-afb3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL_ErLShoU32Nkh6Rq8ODf3vYwsRM1r9A',
    appId: '1:851331446616:ios:5ec0bd8140872810f1d72d',
    messagingSenderId: '851331446616',
    projectId: 'bustracker-afb3c',
    storageBucket: 'bustracker-afb3c.firebasestorage.app',
    iosBundleId: 'com.agni.bus.tracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL_ErLShoU32Nkh6Rq8ODf3vYwsRM1r9A',
    appId: '1:851331446616:ios:5ec0bd8140872810f1d72d',
    messagingSenderId: '851331446616',
    projectId: 'bustracker-afb3c',
    storageBucket: 'bustracker-afb3c.firebasestorage.app',
    iosBundleId: 'com.agni.bus.tracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL_ErLShoU32Nkh6Rq8ODf3vYwsRM1r9A',
    appId: '1:851331446616:web:5ec0bd8140872810f1d72d',
    messagingSenderId: '851331446616',
    projectId: 'bustracker-afb3c',
    authDomain: 'bustracker-afb3c.firebaseapp.com',
    storageBucket: 'bustracker-afb3c.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDL_ErLShoU32Nkh6Rq8ODf3vYwsRM1r9A',
    appId: '1:851331446616:web:5ec0bd8140872810f1d72d',
    messagingSenderId: '851331446616',
    projectId: 'bustracker-afb3c',
    authDomain: 'bustracker-afb3c.firebaseapp.com',
    storageBucket: 'bustracker-afb3c.firebasestorage.app',
  );
}
